name: build_image

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    tags:
      - '*.*.*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set build tag
        run: |
          if [[ "$GITHUB_REF" == *"tags"* ]]; then
          RELEASE_VERSION=${GITHUB_REF#refs/*/}
          else
          RELEASE_VERSION=latest
          fi
          echo "RELEASE_VERSION=${RELEASE_VERSION}" >> $GITHUB_ENV
          echo "Building tag: $RELEASE_VERSION"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ghcr.io/aurorastation/web-interface:${{ env.RELEASE_VERSION }}
          cache-from: type=gha
          cache-to: type=gha,mode=max